# CHANGELOG
# - 2026-02-17: Added automated generation of docs/reference/index.md from source comments.
# - 2026-02-17: Initial version.
# ============================================================================
# Script: scripts/generate_reference_docs.R
# Purpose: Generate markdown API and script reference content from project R
#   source files and write it to docs/reference/index.md.
# Inputs: R source files under R/, code/, and top-level scripts listed in
#   `source_paths`.
# Outputs: docs/reference/index.md
# Assumptions:
#   - Script runs from repository root.
#   - Function definitions follow '<name> <- function(...)' format.
#   - Optional roxygen comments begin with '#\'' directly above functions.
# How to run: Rscript scripts/generate_reference_docs.R
# Notes: This script is documentation-only and must not modify runtime logic.
# ============================================================================

# ---- Setup -----------------------------------------------------------------
# What this section does:
#   - Defines output locations and source paths for reference generation.
# Why it matters:
#   - Keeps generation deterministic and scoped to documented public modules.
# Outputs:
#   - `source_paths` and `reference_output_path` objects.
reference_output_path <- file.path("docs", "reference", "index.md")
source_paths <- c(
  file.path("R", "config.R"),
  file.path("R", "utils.R"),
  file.path("code", "URL_DIGEST.R"),
  file.path("code", "find_excel_path.R"),
  file.path("code", "download_files.R"),
  "main.R",
  "install_dependencies.R",
  "update_project_metadata.R"
)

# ---- Validate assumptions ---------------------------------------------------
# What this section does:
#   - Verifies required source files and output directory are available.
# Why it matters:
#   - Fails fast with clear errors when repository structure changes.
# Outputs:
#   - Ensured output directory for generated reference markdown.
missing_source_paths <- source_paths[!file.exists(source_paths)]
if (length(missing_source_paths) > 0) {
  stop(
    "Missing required source files: ",
    paste(missing_source_paths, collapse = ", ")
  )
}

reference_output_dir <- dirname(reference_output_path)
if (!dir.exists(reference_output_dir)) {
  dir.create(reference_output_dir, recursive = TRUE, showWarnings = FALSE)
}

# ---- Transform --------------------------------------------------------------
# What this section does:
#   - Parses each source file for function definitions and nearest roxygen text.
# Why it matters:
#   - Produces up-to-date reference content without hand-maintained duplication.
# Outputs:
#   - `reference_lines` markdown lines for the generated reference page.
reference_lines <- c(
  "# API and Script Reference",
  "",
  "This page is generated by `scripts/generate_reference_docs.R`.",
  "",
  paste0("Generated on: `", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "`"),
  "",
  "## Included Sources",
  ""
)

for (source_path in source_paths) {
  reference_lines <- c(reference_lines, paste0("- `", source_path, "`"))
}

reference_lines <- c(reference_lines, "", "## Function Inventory", "")

function_pattern <- "^[[:space:]]*([`%[:alnum:]_.]+)[[:space:]]*<-[[:space:]]*function[[:space:]]*\\("

for (source_path in source_paths) {
  source_lines <- readLines(source_path, warn = FALSE)
  function_indexes <- grep(function_pattern, source_lines, perl = TRUE)

  if (length(function_indexes) == 0) {
    next
  }

  reference_lines <- c(reference_lines, paste0("### `", source_path, "`"), "")

  for (function_index in function_indexes) {
    signature_line <- trimws(source_lines[function_index])
    function_name <- sub(
      "^[[:space:]]*([`%[:alnum:]_.]+)[[:space:]]*<-[[:space:]]*function[[:space:]]*\\(.*$",
      "\\1",
      signature_line,
      perl = TRUE
    )

    roxygen_index <- function_index - 1
    while (roxygen_index > 0 && !nzchar(trimws(source_lines[roxygen_index]))) {
      roxygen_index <- roxygen_index - 1
    }
    roxygen_block <- character(0)

    while (roxygen_index > 0 && grepl("^[[:space:]]*#'", source_lines[roxygen_index])) {
      roxygen_block <- c(source_lines[roxygen_index], roxygen_block)
      roxygen_index <- roxygen_index - 1
    }

    roxygen_text <- gsub("^[[:space:]]*#'[[:space:]]?", "", roxygen_block)
    roxygen_text <- roxygen_text[nzchar(trimws(roxygen_text))]

    description_candidates <- roxygen_text[!grepl("^@", roxygen_text)]
    function_summary <- if (length(description_candidates) > 0) {
      description_candidates[1]
    } else {
      "No roxygen summary available."
    }

    parameter_lines <- roxygen_text[grepl("^@param[[:space:]]+", roxygen_text)]
    return_lines <- roxygen_text[grepl("^@return[[:space:]]+", roxygen_text)]

    reference_lines <- c(
      reference_lines,
      paste0("#### `", function_name, "()`"),
      "",
      function_summary,
      "",
      "```r",
      signature_line,
      "```",
      ""
    )

    if (length(parameter_lines) > 0) {
      reference_lines <- c(reference_lines, "Parameters:", "")
      for (parameter_line in parameter_lines) {
        reference_lines <- c(
          reference_lines,
          paste0("- `", sub("^@param[[:space:]]+([^[:space:]]+).*$", "\\1", parameter_line),
                 "`: ",
                 sub("^@param[[:space:]]+[^[:space:]]+[[:space:]]*", "", parameter_line))
        )
      }
      reference_lines <- c(reference_lines, "")
    }

    if (length(return_lines) > 0) {
      reference_lines <- c(
        reference_lines,
        paste0("Returns: ", sub("^@return[[:space:]]+", "", return_lines[1])),
        ""
      )
    }
  }
}

# ---- Output ----------------------------------------------------------------
# What this section does:
#   - Writes generated markdown and logs a summary message.
# Why it matters:
#   - Makes docs generation traceable in CI and local workflows.
# Outputs:
#   - Updated docs/reference/index.md file.
writeLines(reference_lines, reference_output_path)

message(
  "Wrote ",
  length(reference_lines),
  " lines to: ",
  reference_output_path
)

# ---- Sanity checks ----------------------------------------------------------
# What this section does:
#   - Verifies output exists and is non-empty.
# Why it matters:
#   - Prevents silent CI passes with missing reference content.
if (!file.exists(reference_output_path)) {
  stop("Reference output file was not created: ", reference_output_path)
}

if (file.info(reference_output_path)$size <= 0) {
  stop("Reference output file is empty: ", reference_output_path)
}
